# Generated by Django 5.2.2 on 2025-06-09 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceFase',
            fields=[
                ('id', models.AutoField(db_column='ID_Avance', primary_key=True, serialize=False)),
                ('fase', models.CharField(db_column='Fase', max_length=20)),
                ('fecha_cambio', models.DateTimeField(db_column='Fecha_Cambio')),
                ('comentario', models.CharField(blank=True, db_column='Comentario', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Avance_Fase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasesTorneo',
            fields=[
                ('id', models.AutoField(db_column='ID_Base', primary_key=True, serialize=False)),
                ('descripcion_base', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Bases_Torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(db_column='ID_Cancha', primary_key=True, serialize=False)),
                ('nombre_cancha', models.CharField(db_column='Nombre_Cancha', max_length=50)),
            ],
            options={
                'db_table': 'Canchas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadCancha',
            fields=[
                ('id', models.AutoField(db_column='ID_Disponibilidad', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora_inicio', models.TimeField(db_column='Hora_Inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_Fin')),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
            ],
            options={
                'db_table': 'DisponibilidadCancha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(db_column='ID_Equipo', primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(db_column='Nombre_Equipo', max_length=50)),
                ('color_uniforme', models.CharField(db_column='Color_Uniforme', max_length=50)),
                ('estado_equipo', models.CharField(db_column='Estado_Equipo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_modificacion', models.DateTimeField(db_column='Fecha_Modificacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Equipos/')),
                ('creado_por', models.CharField(db_column='Creado_Por', max_length=50)),
            ],
            options={
                'db_table': 'Equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.AutoField(db_column='ID_Goleador', primary_key=True, serialize=False)),
                ('goles', models.IntegerField(db_column='Goles')),
            ],
            options={
                'db_table': 'Goleador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(db_column='ID_Grupo', primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(db_column='Nombre_Grupo', max_length=50)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialCambiosResultado',
            fields=[
                ('id', models.AutoField(db_column='ID_Historial', primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(db_column='Fecha_Cambio')),
                ('modificado_por', models.CharField(db_column='Modificado_Por', max_length=50)),
                ('detalles_cambio', models.CharField(db_column='Detalles_Cambio', max_length=255)),
            ],
            options={
                'db_table': 'Historial_Cambios_Resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSuspension',
            fields=[
                ('id', models.AutoField(db_column='ID_Historial', primary_key=True, serialize=False)),
                ('fecha_suspension', models.DateField(db_column='Fecha_Suspension')),
                ('motivo', models.CharField(db_column='Motivo', max_length=100)),
                ('estado_antes', models.BooleanField(db_column='Estado_Antes')),
                ('estado_despues', models.BooleanField(db_column='Estado_Despues')),
            ],
            options={
                'db_table': 'Historial_Suspension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(db_column='ID_Inscripcion', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(db_column='Fecha_Solicitud')),
            ],
            options={
                'db_table': 'Inscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(db_column='ID_Jornada', primary_key=True, serialize=False)),
                ('numero_jornada', models.IntegerField(db_column='Numero_Jornada')),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('fecha_fin', models.DateField(db_column='Fecha_Fin')),
            ],
            options={
                'db_table': 'Jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(db_column='ID_Participante', primary_key=True, serialize=False)),
                ('carnet', models.CharField(db_column='Carnet', max_length=50)),
                ('nombre_estudiante', models.CharField(db_column='Nombre_Estudiante', max_length=50)),
                ('apellido_estudiante', models.CharField(db_column='Apellido_Estudiante', max_length=50)),
                ('carrera_estudiante', models.CharField(db_column='Carrera_Estudiante', max_length=100)),
                ('semestre_estudiante', models.CharField(db_column='Semestre_Estudiante', max_length=40)),
                ('estado_activo', models.BooleanField(db_column='Estado_Activo', default=True)),
            ],
            options={
                'db_table': 'Participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(db_column='ID_Partidos', primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(db_column='Hora_Inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_Fin')),
                ('fecha_partido', models.DateField(db_column='Fecha_Partido')),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion', default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='Fecha_Modificacion')),
                ('creado_por', models.CharField(blank=True, db_column='Creado_Por', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('Jugado', 'Jugado'), ('Aplazado', 'Aplazado')], db_column='Estado', default='Programado', max_length=20)),
            ],
            options={
                'db_table': 'Partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(db_column='ID_Resultado', primary_key=True, serialize=False)),
                ('goles_equipo', models.IntegerField(db_column='Goles_Equipo')),
                ('tarjetas_amarillas', models.IntegerField(db_column='Tarjetas_Amarillas')),
                ('tarjetas_rojas', models.IntegerField(db_column='Tarjetas_Rojas')),
                ('puntos_equipo', models.IntegerField(db_column='Puntos_Equipo')),
                ('tipo_resultado', models.CharField(db_column='Tipo_Resultado', max_length=20)),
            ],
            options={
                'db_table': 'Resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.AutoField(db_column='ID_Posicion', primary_key=True, serialize=False)),
                ('partidos_jugados', models.IntegerField(db_column='Partidos_Jugados', default=0)),
                ('ganados', models.IntegerField(db_column='Ganados', default=0)),
                ('empatados', models.IntegerField(db_column='Empatados', default=0)),
                ('perdidos', models.IntegerField(db_column='Perdidos', default=0)),
                ('goles_favor', models.IntegerField(db_column='Goles_Favor', default=0)),
                ('goles_contra', models.IntegerField(db_column='Goles_Contra', default=0)),
                ('puntos', models.IntegerField(db_column='Puntos', default=0)),
            ],
            options={
                'db_table': 'Tabla_Posiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(db_column='ID_Tarjeta', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='Fecha_Registro')),
            ],
            options={
                'db_table': 'Tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(db_column='ID_Torneo', primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion_torneo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(max_length=50)),
                ('maximo_equipos', models.IntegerField()),
                ('numero_grupos', models.IntegerField()),
                ('fase_actual', models.CharField(choices=[('Fase de grupos', 'Fase de grupos'), ('Semifinal', 'Semifinal'), ('Final', 'Final'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='torneos/')),
                ('fecha_inicio_inscripcion', models.DateField(blank=True, null=True)),
                ('fecha_fin_inscripcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre_rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Administrador', 'Administrador'), ('Couch', 'Couch')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
