# Generated by Django 5.2 on 2025-05-12 23:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id_arbitro', models.AutoField(db_column='ID_Arbitro', primary_key=True, serialize=False)),
                ('nombre_arbitro', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Nombre_Arbitro', max_length=100, null=True)),
            ],
            options={
                'db_table': 'arbitro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArbitroPartido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Arbitro_Partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('ID_Calendario', models.AutoField(db_column='ID_Calendario', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('dia_semana', models.CharField(db_column='Dia_Semana', max_length=20)),
                ('hora', models.DateTimeField(db_column='Hora')),
            ],
            options={
                'db_table': 'Calendario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canchas',
            fields=[
                ('ID_Cancha', models.AutoField(db_column='ID_Cancha', primary_key=True, serialize=False)),
                ('nombre_cancha', models.CharField(db_column='Nombre_Cancha', max_length=50)),
                ('estado_cancha', models.CharField(db_column='Estado_Cancha', max_length=50)),
            ],
            options={
                'db_table': 'Canchas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('ID_Coach', models.AutoField(db_column='ID_Coach', primary_key=True, serialize=False)),
                ('nombre_coach', models.CharField(db_column='Nombre_Coach', max_length=50)),
                ('puntos_coach1', models.IntegerField(db_column='Puntos_Coach1')),
                ('puntos_coach2', models.IntegerField(db_column='Puntos_Coach2')),
                ('estado_partido', models.CharField(db_column='Estado_Partido', max_length=50)),
            ],
            options={
                'db_table': 'Coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTorneo',
            fields=[
                ('ID_Configuracion', models.AutoField(db_column='ID_Configuracion', primary_key=True, serialize=False)),
                ('puntos_ganado', models.IntegerField(db_column='Puntos_Ganado')),
                ('puntos_empatado', models.IntegerField(db_column='Puntos_Empatado')),
                ('puntos_perdido', models.IntegerField(db_column='Puntos_Perdido')),
                ('puntos_no_presentado', models.IntegerField(db_column='Puntos_No_Presentado')),
                ('tarjetas_amarillas_suspension', models.IntegerField(db_column='Tarjetas_Amarillas_Suspension')),
                ('tarjetas_rojas_suspension', models.IntegerField(db_column='Tarjetas_Rojas_Suspension')),
            ],
            options={
                'db_table': 'Configuracion_Torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('ID_Equipo', models.AutoField(db_column='ID_Equipo', primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(db_column='Nombre_Equipo', max_length=50)),
                ('color_uniforme', models.CharField(db_column='Color_Uniforme', max_length=50)),
                ('estado_equipo', models.CharField(db_column='Estado_Equipo', max_length=50)),
                ('foto_equipo', models.CharField(db_column='Foto_Equipo', max_length=40)),
            ],
            options={
                'db_table': 'Equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id_goleador', models.AutoField(db_column='ID_Goleador', primary_key=True, serialize=False)),
                ('goles', models.IntegerField(blank=True, db_column='Goles', null=True)),
            ],
            options={
                'db_table': 'goleador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('ID_Grupo', models.AutoField(db_column='ID_Grupo', primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(db_column='Nombre_Grupo', max_length=50)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Grupo_Equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialCambiosResultado',
            fields=[
                ('id_historial', models.AutoField(db_column='ID_Historial', primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(blank=True, db_column='Fecha_Cambio', null=True)),
                ('modificado_por', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Modificado_Por', max_length=50, null=True)),
                ('detalles_cambio', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Detalles_Cambio', max_length=255, null=True)),
            ],
            options={
                'db_table': 'historial_cambios_resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSuspension',
            fields=[
                ('id_historial', models.AutoField(db_column='ID_Historial', primary_key=True, serialize=False)),
                ('fecha_suspension', models.DateField(blank=True, db_column='Fecha_Suspension', null=True)),
                ('motivo', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Motivo', max_length=100, null=True)),
                ('estado_antes', models.TextField(blank=True, db_column='Estado_Antes', null=True)),
                ('estado_despues', models.TextField(blank=True, db_column='Estado_Despues', null=True)),
            ],
            options={
                'db_table': 'historial_suspension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('ID_Horario', models.AutoField(db_column='ID_Horario', primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(db_column='Hora_Inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_Fin')),
            ],
            options={
                'db_table': 'Horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('ID_Jornada', models.AutoField(db_column='ID_Jornada', primary_key=True, serialize=False)),
                ('numero_jornada', models.IntegerField(db_column='Numero_Jornada')),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('fecha_fin', models.DateField(db_column='Fecha_Fin')),
            ],
            options={
                'db_table': 'Jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('ID_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(db_column='Nombre_Estudiante', max_length=50)),
                ('apellido_estudiante', models.CharField(db_column='Apellido_Estudiante', max_length=50)),
                ('carrera_estudiante', models.CharField(db_column='Carrera_Estudiante', max_length=100)),
                ('semestre_estudiante', models.CharField(db_column='Semestre_Estudiante', max_length=40)),
                ('estado_activo', models.BooleanField(db_column='Estado_Activo', default=True, null=True)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipanteEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_capitan', models.BooleanField(db_column='Es_Capitan', default=False)),
            ],
            options={
                'db_table': 'Participante_Equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantePartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Participante_Partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('ID_Partidos', models.AutoField(db_column='ID_Partidos', primary_key=True, serialize=False)),
                ('fecha_partido', models.DateField(db_column='Fecha_Partido')),
                ('hora_partido', models.TimeField(db_column='Hora_Partido')),
            ],
            options={
                'db_table': 'Partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartidoCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Partido_Cancha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('ID_Resultado', models.AutoField(db_column='ID_Resultado', primary_key=True, serialize=False)),
                ('puntos_equipo', models.IntegerField(db_column='Puntos_Equipo')),
                ('tarjetas_amarillas', models.IntegerField(db_column='Tarjetas_Amarillas')),
                ('tarjetas_rojas', models.IntegerField(db_column='Tarjetas_Rojas')),
                ('goles_equipo', models.IntegerField(db_column='Goles_Equipo')),
            ],
            options={
                'db_table': 'Resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('ID_Sancion', models.AutoField(db_column='ID_Sancion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Amarilla', 'Amarilla'), ('Roja', 'Roja')], db_column='Tipo', max_length=20)),
                ('fecha_Sancion', models.DateField(db_column='Fecha_Sancion')),
            ],
            options={
                'db_table': 'Sancion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id_posicion', models.AutoField(db_column='ID_Posicion', primary_key=True, serialize=False)),
                ('partidos_jugados', models.IntegerField(blank=True, db_column='Partidos_Jugados', null=True)),
                ('ganados', models.IntegerField(blank=True, db_column='Ganados', null=True)),
                ('empatados', models.IntegerField(blank=True, db_column='Empatados', null=True)),
                ('perdidos', models.IntegerField(blank=True, db_column='Perdidos', null=True)),
                ('goles_favor', models.IntegerField(blank=True, db_column='Goles_Favor', null=True)),
                ('goles_contra', models.IntegerField(blank=True, db_column='Goles_Contra', null=True)),
                ('puntos', models.IntegerField(blank=True, db_column='Puntos', null=True)),
            ],
            options={
                'db_table': 'tabla_posiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('ID_torneo', models.AutoField(db_column='ID_Torneo', primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(db_column='Nombre_Torneo', max_length=40)),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('fecha_fin', models.DateField(db_column='Fecha_Fin')),
                ('descripcion_torneo', models.CharField(db_column='Descripcion_Torneo', max_length=200)),
                ('fecha_creacion', models.DateTimeField(blank=True, db_column='Fecha_Creacion', null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, db_column='Fecha_Modificacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='Creado_Por', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
