# Generated by Django 5.2 on 2025-06-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitorneos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
